### ISSUE TITLE
Pick me another story not generating another story

### ISSUE THREAD

**Issue by jermyk** [Heydon/niace-stories-app#71]
When the user clicks on the "pick me another story" button the same story that was originally selected is still displayed
![screenshot_011615_034424_pm](https://cloud.githubusercontent.com/assets/4446325/5778912/8e38bfc8-9d96-11e4-8993-27ce414fc3e1.jpg)

**Comment by Heydon** [comment]
Thanks, Karl. This is now covered in #72
